# The following secret variables are at organisation-level: CI_TOKEN, HOST_USERNAME, PRIVATE_KEY
# Only, *_IP is repository-dependent

name: CI/CD Pipeline for production

on:
  push:
    branches: main

jobs:
  build_and_deploy:
    runs-on: self-hosted
   
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.CI_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Export ENV Variables
        run: |
          IMAGE_NAME=$(basename "`pwd`" )
          IMAGE_TAG=$(cat ./VERSION)
          APP_PORT=$(cat ./scripts/port.txt)
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "APP_PORT=${APP_PORT}" >> $GITHUB_ENV

      - name: Print ENV Variables
        run: |
          echo  $IMAGE_NAME
          echo  $IMAGE_TAG
          echo  $APP_PORT

      - name: Save Private Key
        run: |
          printf "%s\n" """${{secrets.SSH_PRIVATE_KEY}}""" > ./privatekey
          chmod 400 ./privatekey
    
      - name: Build and Push Docker Image
        run: |
          docker build . -t ${IMAGE_NAME}:${IMAGE_TAG}
          docker save $IMAGE_NAME:$IMAGE_TAG | bzip2 | ssh -o StrictHostKeyChecking=no  -i ./privatekey ${{ secrets.HOST_USERNAME }}@${{ secrets.PROD_IP }} docker load

      - name: Run Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no  -i ./privatekey ${{ secrets.HOST_USERNAME }}@${{ secrets.PROD_IP }} "~/infrastructure-server/scripts/docker-management/run-image.sh $IMAGE_NAME $IMAGE_TAG $APP_PORT"