# The following secret variables are at organisation-level: CI_TOKEN, HOST_USERNAME, PRIVATE_KEY
# Only, *_IP is repository-dependent

name: CI/CD Pipeline for development

on:
  push:
    branches: 
     - develop

jobs:
  checkout-repository:
    runs-on: self-hosted
    steps :
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: "true"
          token: ${{ secrets.CI_TOKEN }}

  build_and_deploy:
    uses: similar-Intelligence/infrastructure-server/.github/workflows/deployment.yml@develop
    secrets: 
     IP: ${{secrets.DEV_IP}}
     HOST_USERNAME: ${{secrets.HOST_USERNAME}}
     SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}