name: "Server Deployment"

on:
  push

env:
  FOLDER_PATH: ~/playground/${{ github.event.repository.name }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync --mkpath -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$FOLDER_PATH
      - name: Install packages
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd $FOLDER_PATH && PATH=\$PATH:~/.pyenv/shims bash scripts/install.sh"
      - name: Run server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd $FOLDER_PATH; PATH=\$PATH:~/.pyenv/shims bash scripts/run.sh"